// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package querytest

import ()

type User struct {
	ID   uint32
	Name string
}

type UserLink struct {
	OwnerID    uint32
	ConsumerID uint32
}
